### ISSUE TITLE
Logo Suggestion

### ISSUE THREAD

**Issue by Iridium-IO** [WrenSecurity/wrensec-branding#2]
I saw your post on [Open Source Design](http://opensourcedesign.net/jobs/jobs/2018-01-28-need-logo-for-wren-security-project) and even though it looks like you might have a logo, I had a go at making one anyway. 
![wrensecurity](https://user-images.githubusercontent.com/1491536/38160319-0dba04f2-34ff-11e8-8150-b4b913253525.png)

Here's the PDF vector: 
[WrenSecurity.pdf](https://github.com/WrenSecurity/wrensec-branding/files/1865205/WrenSecurity.pdf)

**Comment by asierdqb** [comment]
#imminentfate Thanks for the contribution. Could you have a look at the six submission templates here please. https://github.com/WrenSecurity/wrensec-branding/find/master?q=

**Comment by asierdqb** [comment]
#imminentfate  The 6 templates are SVG files. Names starting with numbered 1 to 6, followed by "-wren-logo-submit-..."
Have a look in the repo Wiki for more information and examples of submitted logos.
If any problems give me shout.

Asier
